# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5db9f6426b0a9ae3442a05cc47b93395d1a72b309f1f0a47b935e3fa81bd9ea145c84ab7f6efeb4fbabc4cde223c5c6761529d94f7071f6f0394fe2f44877ef4

test:
  secret_key_base: c4492258919b0e7caf780357683cfa77e0beba34cb0dbce8897aefdd237f7d5e14d7993a8b63d684bacbf831ff7e18219fef49e5a47e734fef224687fec3b453

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
